[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]
exclude = ["tests/fixtures"]

[tool.mypy]
python_version = "3.13"
check_untyped_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_optional = true
exclude = ["tests/fixtures"]

explicit_package_bases = true

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
